---
version: "3.9"
services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=testnet
      - POSTGRES_USER=testnet
      - POSTGRES_PASSWORD=testnet

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env.testnet
    environment:
      FLOW_PDS_ADMIN_ADDRESS: 070704779ca994b7
      FLOW_PDS_ADMIN_PRIVATE_KEY:
      FLOW_PDS_ADMIN_PRIVATE_KEY_INDEXES: 0
      FLOW_PDS_ADMIN_PRIVATE_KEY_TYPE: local
      FLOW_PDS_DATABASE_DSN: postgresql://testnet:testnet@db:5432/testnet
      FLOW_PDS_DATABASE_TYPE: psql
      FLOW_PDS_ACCESS_API_HOST: access.devnet.nodes.onflow.org:9000
      PDS_ADDRESS: 070704779ca994b7 # PDS account address
      NON_FUNGIBLE_TOKEN_ADDRESS: 631e88ae7f1d7c20
