version: "3.9"
services:
  test-db:
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  test-emulator:
    image: gcr.io/flow-container-registry/emulator:v0.23.0
    restart: unless-stopped
    command: emulator -v
    ports:
      - "3569:3569"
    env_file:
      - ./.env
    environment:
      - FLOW_SERVICEPRIVATEKEY=27f93302f5851077d63ece5b693094c0e5fc0a169369069fa8fb6a134ffc0eab
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
      - FLOW_TRANSACTIONFEESENABLED=true
