openapi: 3.0.0
info:
  title: Flow PDS API
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000/v1'
paths:
  /distributions:
    post:
      summary: Create Distribution
      operationId: create-distribution
      responses:
        '201':
          $ref: '#/components/responses/Distribution-Create-Ok'
        '400':
          $ref: '#/components/responses/Distribution-Create-Error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                distId:
                  type: integer
                  format: int64
                  minimum: 0
                  example: 1
                issuer:
                  $ref: ../models/Distribution-Issuer.yaml
                meta:
                  $ref: ../models/Distribution-Meta.yaml
                packTemplate:
                  $ref: ../models/Pack-Template.yaml
              required:
                - issuer
                - meta
                - packTemplate
            examples:
              example-1:
                value:
                  distId: 12
                  issuer: '0x1'
                  meta:
                    title: string
                    description: string
                    image: string
                    startDate: '2019-08-24T14:15:22Z'
                    endDate: '2019-08-24T14:15:22Z'
                  packTemplate:
                    packReference:
                      name: string
                      address: '0x1'
                    collectibleReference:
                      name: string
                      address: '0x1'
                    packCount: 3
                    buckets:
                      - collectibleCount: 2
                        collectibleCollection:
                          - 1
                          - 2
                          - 3
                          - 4
                          - 5
                          - 6
                          - 7
                          - 8
                          - 9
                          - 10
      description: 'Create a distribution. If template is valid, a distribution is created in database and the id is returned. All the related tasks are started asynchronously (settling and minting).'
    parameters: []
    get:
      summary: List distributions
      operationId: list-distributions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/DistributionListItem.yaml
      description: List all distributions in the database.
      parameters:
        - schema:
            type: number
            minimum: 0
            maximum: 1000
            default: 1000
          in: query
          name: limit
        - schema:
            type: number
            minimum: 0
          in: query
          name: offset
  '/distributions/{distributionId}':
    parameters:
      - schema:
          type: string
        name: distributionId
        in: path
        required: true
    get:
      summary: Get Distribution
      operationId: get-distribution-by-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Distribution.yaml
      description: Returns the details for a distribution.
  '/distributions/{distributionId}/cancel':
    parameters:
      - schema:
          type: string
        name: distributionId
        in: path
        required: true
    delete:
      summary: Cancel distribution
      operationId: cancel-distribution
      responses:
        '200':
          description: OK
      description: Cancel a distribution which is not in "complete" state. PDS should return all withdrawn NFTs and once all have been returned revoke all capabilities created during this distribution and delete the distribution from database.
components:
  schemas: {}
  responses:
    Distribution-Create-Ok:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              distributionId:
                type: string
    Distribution-Create-Error:
      description: Example response
      content:
        text/plain:
          schema:
            type: string
