openapi: 3.0.0
info:
  title: Flow PDS API
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000/v1'
paths:
  /health/ready:
    get:
      summary: Health check
      description: 'Simple health check, will always respond with 200 OK'
      operationId: health-ready
      responses:
        '200':
          description: OK
  /set-dist-cap:
    post:
      summary: 'Set distribution capability'
      operationId: set-dist-cap
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
              examples: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
              examples: {}
      description: Share the create distribution capability to issuer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                issuer:
                  $ref: ../models/Issuer.yaml
            examples:
              example-1:
                value:
                  issuer: '0x1'
  /distributions:
    post:
      summary: Create Distribution
      operationId: create-distribution
      responses:
        '201':
          $ref: '#/components/responses/Distribution-Create-Ok'
        '400':
          $ref: '#/components/responses/Distribution-Create-Error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                distFlowID:
                  type: integer
                  minimum: 0
                  example: 1
                issuer:
                  $ref: ../models/Issuer.yaml
                packTemplate:
                  $ref: ../models/Pack-Template-Create.yaml
              required:
                - distFlowID
                - issuer
                - packTemplate
            examples:
              example-1:
                value:
                  distFlowID: 1
                  issuer: '0x1'
                  packTemplate:
                    packReference:
                      name: ExampleNFT
                      address: '0x1'
                    collectibleReference:
                      name: ExampleNFT
                      address: '0x1'
                    packCount: 1
                    buckets:
                      - collectibleCount: 4
                        collectibleCollection:
                          - 1
                          - 2
                          - 3
                          - 4
                          - 5
                          - 6
                          - 7
                          - 8
                          - 9
                          - 10
        description: ''
      description: 'Create a distribution. If template is valid, a distribution is created in database and both the offchain (distID) and the onchain (distFlowID) IDs are returned. All the related tasks are started asynchronously (settling and minting).'
    parameters: []
    get:
      summary: List distributions
      operationId: list-distributions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Distribution-List.yaml
      description: List all distributions in the database.
      parameters:
        - schema:
            type: number
            minimum: 0
            maximum: 1000
            default: 1000
          in: query
          name: limit
        - schema:
            type: number
            minimum: 0
          in: query
          name: offset
  '/distributions/{distributionId}':
    parameters:
      - schema:
          type: string
        name: distributionId
        in: path
        required: true
        description: Distribution offchain ID
    get:
      summary: Get Distribution
      operationId: get-distribution-by-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Distribution-Get.yaml
      description: Returns the details for a distribution.
  '/distributions/{distributionId}/abort':
    parameters:
      - schema:
          type: string
        name: distributionId
        in: path
        required: true
        description: Distribution offchain ID
    post:
      summary: Abort distribution
      operationId: abort-distribution
      responses:
        '200':
          description: OK
      description: 'Forcibly abort the process, which will put the Distribution into the Invalid state.'
components:
  schemas: {}
  responses:
    Distribution-Create-Ok:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              distID:
                type: string
                format: uuid
              distFlowID:
                type: integer
    Distribution-Create-Error:
      description: Example response
      content:
        text/plain:
          schema:
            type: string
